title:              Christelle Zouein
email:              christellezouein@hotmail.com
description:        Hello and welcome to my website! Here you can find out more about me, my projects and my background as a computer engineering student.
author:             Christelle Zouein
baseurl:            ""
url:                "http://chzn.fr"

# Social Profiles
twitter_username:   
github_username:    christellezouein
facebook_username:  
instagram_username:  
linkedin_username:  christelle-zouein

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
